---
# file: roles/common/tasks/etckeeper.yml

- name: be sure etckeeper is installed
  apt: pkg={{ item }} state=installed
  with_items:
    - git
    - etckeeper
  tags:
    - packages
    - etckeeper
  notify:
    - initialize etckeeper
